version: "3.7"
services:
  client:
    build:
      context: ./client
    image: muc-client
    networks:
      - muc
    ports:
      - "5000:5000"
    restart: always
  server:
    build:
      context: ./server
    environment:
      - NODE_ENV=production
    image: muc-server
    networks:
      - muc
    ports:
      - "9001:9001"
    restart: always
networks:
  muc:
